// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcCipu7t-tvLEfMuvx_piqUaQ2X8i2Ro0',
    appId: '1:668547710656:web:d976d19bcf1c5a9da3f725',
    messagingSenderId: '668547710656',
    projectId: 'otpphone-d70a1',
    authDomain: 'otpphone-d70a1.firebaseapp.com',
    storageBucket: 'otpphone-d70a1.appspot.com',
    measurementId: 'G-FX8S69G6L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjvwLfR2GxqawtY6mB24bSABfOp2GSsE',
    appId: '1:668547710656:android:81dde8790df39fe1a3f725',
    messagingSenderId: '668547710656',
    projectId: 'otpphone-d70a1',
    storageBucket: 'otpphone-d70a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSj_v5D9qrEFSCBHSKvpNf8zcJEjujGB0',
    appId: '1:668547710656:ios:4c108779ca45cec9a3f725',
    messagingSenderId: '668547710656',
    projectId: 'otpphone-d70a1',
    storageBucket: 'otpphone-d70a1.appspot.com',
    androidClientId: '668547710656-4bjabokq6o82pujq62al9kj4v0l0dfr2.apps.googleusercontent.com',
    iosClientId: '668547710656-3bjuvhoj215hap92b0clcj05mnkcja4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSj_v5D9qrEFSCBHSKvpNf8zcJEjujGB0',
    appId: '1:668547710656:ios:4c108779ca45cec9a3f725',
    messagingSenderId: '668547710656',
    projectId: 'otpphone-d70a1',
    storageBucket: 'otpphone-d70a1.appspot.com',
    androidClientId: '668547710656-4bjabokq6o82pujq62al9kj4v0l0dfr2.apps.googleusercontent.com',
    iosClientId: '668547710656-3bjuvhoj215hap92b0clcj05mnkcja4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneOtp',
  );
}
